# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GROUP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(blank=True, editable=False, max_length=30, verbose_name='\u7528\u6237\u540d\u79f0')),
                ('user_school', models.CharField(blank=True, editable=False, max_length=60, verbose_name='\u7528\u6237\u5b66\u9662')),
            ],
            options={
                'db_table': 'my_user_group',
                'verbose_name': '\u7528\u6237\u6743\u9650\u8868',
            },
        ),
    ]
